config/routes.rb
Rails.application.routes.draw do
  root 'people#index'

  resources :people
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
    
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to person_path(@person.id)
    else
      render :new
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def destroy
    Person.find(params[:id]).destroy
    redirect_to root_path
  end

  private
    def person_params
      params.require(:person).permit(:first_name, :last_name, :avatar, :phone, :email)
    end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friendbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: @person, class: 'ui form') do |f| %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name, required: true %>
    <br />
    <%= f.label :last_name %>
    <%= f.text_field :last_name, required: true %>
    <br />
    <%= f.label :avatar %>
    <%= f.text_field :avatar %>
    <br />
    <%= f.label :email %>
    <%= f.text_field :email %>
    <br />
    <%= f.label :phone %>
    <%= f.text_field :phone %>
    <br />
    <%= f.submit nil, class: 'ui button primary' %>
  <% end %>

app/views/people/edit.html.erb
<%= render 'form' %>

app/views/people/index.html.erb
<h1 class="ui header">People</h1>
<%= link_to 'New Person', new_person_path %>
<div class="ui divider"></div>

<div class="ui grid">
  <% @people.each do |person| %>
    <div class="sixteen wide mobile eight wide tablet four wide computer column">
      <div class="ui card">
        <div class="image">
          <img src="https://robohash.org/<%= person.avatar %>?set=3" />
        </div>
        <div class="content">
        <%= link_to "#{person.first_name} #{person.last_name}", person_path(person.id), class: "header" %>
        </div>
        <div class="extra content">
          <div class="ui two buttons">
            <div class="basic green button">
                <%= link_to 'Edit', edit_person_path(person.id) %>
            </div>
            <div class="basic red button">
                <%= link_to 'Delete', person_path(person.id), method: :delete, data: {confirm: 'Are You Sure?' }  %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/people/new.html.erb
<%= render 'form' %>

app/views/people/show.html.erb
<h1>People#show</h1>
<p>Find me in app/views/people/show.html.erb</p>